/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_api_key": "da2-hdrmr2nmwzf2pfx3oig4wykv6y"
};


export default awsmobile;
